# Identificador del proyecto
sonar.projectKey=ceaa-backend
sonar.projectName=CEAA Backend
sonar.projectVersion=1.0

# Código fuente
sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,coverage/**

# Lenguaje
sonar.language=js
sonar.sourceEncoding=UTF-8

# URL de SonarQube (Docker)
sonar.host.url=http://localhost:9000

# Token (usar variable de entorno)
sonar.token=${SONAR_TOKEN}
